apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bharathisuresh/devops-backend:latest
        imagePullPolicy: Always   # 🔥 VERY IMPORTANT
        ports:
        - containerPort: 5000